#!/bin/bash

if [ "$#" = 0 ]
then
    cat << EOF

ERROR: No arguments have been passed!
        
Use the following command: 
singularity run --cleanenv <container> <batch file> <arguments>
        
For more details, please use the 'help' command:
singularity help <container>

EOF
exit 1
fi